### ISSUE TITLE
lovelace swipe navigation, not load!... at HACS

### ISSUE THREAD

**Issue by Goldenfox007** [maykar/lovelace-swipe-navigation#50]
![not load](https://user-images.githubusercontent.com/48960672/115407690-2a5aa400-a1e8-11eb-84e7-6d8ab753b487.png)

**Comment by KTibow** [comment]
*sighs* Issue reports without a lot of detail never help. Have you tried refreshing the page when HACS prompted you?

**Comment by Marmoulak** [comment]
I have the same problem. I have tried to reinstall. didn't help
running on Raspberry 3 B+

**Comment by maykar** [comment]
When using HACS it should automatically add the files and correct resource to your Lovelace resources. You can check that the resource is being loaded by checking your browser's dev tools console (usually F12) and if it is loaded you will see "Swipe Navigation" and it's current version number listed in the console.

If you do not see it listed in the console, it is not being loaded. This could be because something happened during HACS installation like the resource not being added. To check this go to `Configuration > Lovelace Dashboards > Resources`. You should see a resource with the URL `/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js`, if you do not: Simply click "Add Resource" and paste in the previous URL.

You can also check that HACS installed the files correctly by looking in your config folder and going to the `/www/community/` folder and it should contain the `lovelace-swipe-navigation` folder and inside should be the 2 files: `swipe-navigation.js` and `swipe-navigation.js.gz`. If this is the first time you've added a frontend modification or first time using the /www/ folder, you need to restart HA.

If the resource and file exists and you still do not see Swipe Navigation in your browser's dev tools console or it isn't functioning on a mobile device, you need to clear your cache. Clearing your cache in any browser is pretty self explanatory, the iPhone app has a setting to do so within the app, and on Android I find it easiest to hold the app icon, hit "App info", click "Force Stop", select "Storage & Cache", and click "Clear Cache".

**Comment by maykar** [comment]
If it still doesn't work, check your browser's dev tools console and HA logs for errors pertaining to Swipe Navigation and create an issue report that includes the error(s) and any other info that could be helpful.
